#Só uma base
version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha_do_banco #Mesma senha utilizada no crud.py
      MYSQL_DATABASE: dietas_db #Mesmo nome de banco de dados utilizado em crud.py
